# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Markdown-native task and document tracking"
  homepage "https://github.com/rogersnm/compass"
  version "0.8.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rogersnm/compass/releases/download/v0.8.7/compass_0.8.7_darwin_amd64.tar.gz"
      sha256 "034cf40a1c87a80fda0216fd1c510c09308a50d0ac973286a1abc4e573a3157c"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rogersnm/compass/releases/download/v0.8.7/compass_0.8.7_darwin_arm64.tar.gz"
      sha256 "6f25cc05aec86065b2fa4c64feba913c7b7eaf7f81b45df24c5e45b2d2e06971"

      def install
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rogersnm/compass/releases/download/v0.8.7/compass_0.8.7_linux_amd64.tar.gz"
      sha256 "83adac07392bb34ab3762c58022928e9d63b021a15aee860c6a563a3091bfa31"
      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rogersnm/compass/releases/download/v0.8.7/compass_0.8.7_linux_arm64.tar.gz"
      sha256 "2dc11aad121a60d492076480cdef5e7c83b4033bf592b5d5a870a3bde7a71290"
      def install
        bin.install "compass"
      end
    end
  end
end
