# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Markdown-native task and document tracking"
  homepage "https://github.com/rogersnm/compass"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rogersnm/compass/releases/download/v0.9.0/compass_0.9.0_darwin_amd64.tar.gz"
      sha256 "1594d8787ebeb2cf811cd42cd5b3371c42dcfb2d98dab5dbeb33c6586a1be6bf"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rogersnm/compass/releases/download/v0.9.0/compass_0.9.0_darwin_arm64.tar.gz"
      sha256 "5087f41a56814c631db72c7a47deae55043a83d86979e7deb5fd937eef27ace8"

      def install
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rogersnm/compass/releases/download/v0.9.0/compass_0.9.0_linux_amd64.tar.gz"
      sha256 "3387c4b64692105fdb3440ea0312848ae4c3d62d4135d043570c43e040a353e6"
      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rogersnm/compass/releases/download/v0.9.0/compass_0.9.0_linux_arm64.tar.gz"
      sha256 "05de35e96b6f5fcc55c7c570573ba0b1d120ecdcb152d02cfe0fcea4a4c25857"
      def install
        bin.install "compass"
      end
    end
  end
end
